# Generated by Django 5.1.7 on 2025-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_name_39f70b_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
