# Generated by Django 5.1.7 on 2025-03-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_category_catalog_cat_name_39f70b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subcategory',
            name='catalog_sub_name_5ec2cb_idx',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
    ]
